# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         JavaScript-SpiderMonkey
version:      0.13
version_from: SpiderMonkey.pm
installdirs:  site
requires:
    Data::Dumper:                  
    Log::Log4perl:                 

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
